version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: bible_api_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  bible_api:
    build: .
    container_name: bible_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
